feat: test back

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -1,7 +1,7 @@
 #!/bin/sh
 POSIXLY_CORRECT=yes
-LC_NUMERIC=en_US.UTF-8 #neistota, ci mozno, asi forum bude navstivene (inak mi to mocne zaokruhluje a kraviny pocita)
-
+LC_NUMERIC=en_US.UTF-8 #todo , ci mozno, asi forum bude navstivene (inak mi to mocne zaokruhluje a kraviny pocita)
+#LC_ALL=C.UTF-8
 
 print_hlp_fun() { #prints breaf instruction
     echo "
@@ -65,7 +65,7 @@ ERROR_fun () { #checks basic syntax and returns errors and even more breaf help
     fi
 }
 
-FLT_fun () { #separate function for FILTER based on recursive initial SORT, reusable based on commands
+FLT_fun () { #separate function for FILTER based on recursive initial $ORT, reusable - based on commands
     if [ -n "$FLA" ]; then #after time
         SORT=$(echo "$SORT" | awk -F ";" -v after="$FLA" "{if (after < \$2){print}}" | sort)
     fi
@@ -90,7 +90,7 @@ CMD_fun () { #COMMAND function
     case "$CMD" in
         list | "")
             echo "$SORT"
-            ;; #for list print everyting with used NAME
+            ;; #for list prints everything with used NAME
 
         list-currency)
             echo "$SORT" | awk -F ";" "{print \$3}" | sort | uniq
@@ -109,6 +109,9 @@ CMD_fun () { #COMMAND function
             print}
             }" | sort
             ;; #similar to status, yet multiplies currencies with positive status, then adds, then prints
+        *)
+            echo "ERROR: Please call for '--help'." >&2
+            exit 2
 
     esac
 }
