feat: done (misspelling treated the easy way)

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -1,6 +1,9 @@
 #!/bin/sh
 POSIXLY_CORRECT=yes
-LC_NUMERIC= #todo , forum + 4 desatinne
+LC_NUMERIC=
+
+#login:     xmeciak00
+#author:    Katarina Meciarova
 
 print_hlp_fun() { #prints breaf instruction
     echo "
@@ -26,7 +29,9 @@ print_hlp_fun() { #prints breaf instruction
                     for UŽIVATEL use your name you had signed with
                     for LOG use log, which has to be a file of '.log' or '.gz' in CSV format
 
-                    WARNING: last two (UŽIVATEL & LOG) are mandatory for every action
+
+                    WARNING   :     last two (UŽIVATEL & LOG) are mandatory for every action
+                    WARNING 2 :     commands like PŘÍKAZ and UŽIVATEL can be used only once at a time
 
                     Hope it helped :)
 
@@ -147,48 +152,55 @@ while [ "$#" -gt 0 ]; do #checks for every input - case insensitive
             ;; # code for currency had been added to our bucket list
         list | list-currency | status | profit)
             CMD_counter=$((CMD_counter+1))
-            if [ "$CMD_counter" -eq 1 ]; then
-                CMD="$1" #only for 1 CMD - takes only the last given one
+            if [ "$CMD_counter" -eq 1 ]; then #quick check if only one command was given
+                CMD="$1"
                 shift 1
-            else
-                echo #"ERROR: You can use only one COMMAND at once, check '--help'."
+            else #if not, error warns the user
+                echo "ERROR: You can use only one COMMAND at once, check '--help'."
                 exit 6
             fi
-            ;; # now we know what u want to know. the fact u r dyslectic will be proved in few seconds :)
+            ;;
         *.log | *.gz)
             LOG_counter=$((LOG_counter+1))
-            if [ "$LOG_counter" -eq 1 ]; then
+            if [ "$LOG_counter" -eq 1 ]; then #version for empty log variable
                 case "$1" in
                     *.gz)
                         LOG="${LOG}$(gzip -d -c "$1")"
-                        ;; # now we know everything about you, thanks for your cooperation
+                        ;; # uncompressing gzip and saving into log variable
                     *)
                         LOG="${LOG}$(cat "$1")"
-                        ;; # same, but not for compressed files, just for the standard ones
+                        ;; # saving .log into log variable
                 esac
-            else
+            else #if variable is already filled with some information
                 case "$1" in
                     *.gz)
                         LOG="${LOG} \n$(gzip -d -c "$1")"
-                        ;; # now we know everything about you, thanks for your cooperation
+                        ;;
                     *)
                         LOG="${LOG} \n$(cat "$1")"
-                        ;; # same, but not for compressed files, just for the standard ones
+                        ;;
                 esac
             fi
 
             shift 1
             ;;
         *)
-            NAME="$1"
-            shift 1
-            ;; # todo misspelling check
+            NAME_counter=$((NAME_counter+1))
+            if [ "$NAME_counter" -eq 1 ]; then
+                NAME="$1"
+                shift 1
+            else
+                echo "ERROR: You can use only one name at once. Maybe you just misspelled something, may want to check '--help'."
+                exit 7
+            fi
+
+            ;;
     esac
 done
+ERROR_fun  "$NAME","${LOG}"
 
 # ak jesto, cas prikazom dat priestor
-ERROR_fun  "$NAME","${LOG}" , #checks for your dyslexia
-initial_fun "${LOG}" , #helps my dyslexia
-FLT_fun "$FLA","$FLB","$FLC","$NAME","${LOG}" , #helps your other dysfunctions
-CMD_fun "$CMD","$NAME","${LOG}" , #-||-
-exit 0 #deal done
+initial_fun "${LOG}"
+FLT_fun "$FLA","$FLB","$FLC","$NAME","${LOG}"
+CMD_fun "$CMD","$NAME","${LOG}"
+exit 0
diff --git a/xtf_missspelling b/xtf_missspelling
--- a/xtf_missspelling
+++ b/xtf_missspelling
@@ -43,7 +43,6 @@ DT_format_fun() { #checks for right DT format
 }
 
 serror_fun(){
-
     if [ -z "$SORT" ]; then
         exit 0
     fi
@@ -145,11 +144,98 @@ while [ "$#" -gt 0 ]; do
             shift 1
             ;;
         *)
-            INPUT="$INPUT $1"
+            IN_counter=$((FLC_counter+1))
+            if [ "$IN_counter" -eq 1 ]; then
+                INPUT="$1"
+            else
+                INPUT="$INPUT $1"
+            fi
             shift 1
     esac
 done
 
+FLA=$(echo "$INPUT" | awk -F " " "{
+    for (i = 1; i <= NF; i++)
+        if (\$i == \"-a\")
+        {
+            printf \$(i+1) \" \" \$(i+2)
+        }
+    }")
+FLB=$(echo "$INPUT" | awk -F " " "{
+    for (i = 1; i <= NF; i++)
+        if (\$i == \"-b\")
+        {
+            printf \$(i+1) \" \" \$(i+2)
+        }
+    }")
+FLC=$(echo "$INPUT" | awk -F " " "{
+    for (i = 1; i <= NF; i++)
+        if (\$i == \"-c\")
+        {
+            printf \$(i+1) \" \" \$(i+2)
+        }
+    }")
+CMD=$(echo "$INPUT" | awk -F " " "{
+    for (i = 1; i <= NF; i++)
+        if (\$i == \"-b\")
+        {
+            printf \$(i+1) \" \" \$(i+2)
+        }
+    }")
+NAME=$(echo "$INPUT" | awk -F " " "{
+    for (i = 1; i <= NF; i++)
+        if (\$i == \"-b\")
+        {
+            printf \$(i+1) \" \" \$(i+2)
+        }
+    }")
+
+echo "$INPUT" | while read -r commands; do
+    case "$commands" in
+            -h | --help)
+                print_hlp_fun
+                exit 0
+                ;; # help had been printed
+            -a)
+                DT_format_fun "$2"
+                FLA="$2"
+                shift 2
+                ;; # datetime for AFTER had been taken to better place :)
+            -b)
+                DT_format_fun "$2"
+                FLB="$2"
+                shift 2
+                ;; # -||- BEFORE -||-
+            -c)
+                FLC_counter=$((FLC_counter+1))
+                if [ "$FLC_counter" -eq 1 ]; then
+                    FLC="$2"
+                else
+                    FLC="${FLC} $2"
+                fi
+                shift 2
+                ;; # code for currency had been added to our bucket list
+            list | list-currency | status | profit)
+                CMD_counter=$((CMD_counter+1))
+                if [ "$CMD_counter" -eq 1 ]; then
+                    CMD="$1" #only for 1 CMD - takes only the last given one
+                    shift 1
+                else
+                    echo #"ERROR: You can use only one COMMAND at once, check '--help'."
+                    exit 6
+                fi
+                ;; # now we know what u want to know. the fact u r dyslectic will be proved in few seconds :)
+            *)
+                NAME="$1"
+                shift 1
+                ;; # uh, sry, now we know everything, thanks... muhahahaa
+        esac
+done
+
+
+#todo   sort        INPUT   into FLT, CMD, NAME
+#todo   check       if -n INPUT else than FLT-CMD-NAME then ERROR
+#todo   check       if NAME == LOG awk $1
 
 # skontroluj, ci jesto veci dvesto
 while [ "$#" -gt 0 ]; do #checks for every input - case insensitive
