feat: done nah

diff --git a/proj1/xtf b/proj1/xtf
--- a/proj1/xtf
+++ b/proj1/xtf
@@ -86,8 +86,9 @@ ERROR_fun () { #checks basic syntax and returns errors and even more breaf help
             ;;
         4)
             echo "${LOG}" | while IFS= read -r line; do
-                if echo "$line" | grep -Pq "^[!-~]\+;[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\};
-                                                                            [A-Z]\{3\};[+-]*[0-9]\+\.[0-9]\{4\}$"; then
+                LINE=$(echo "$line" | grep -Pq "^[!-~]+;[0-9]{4}\-[0-9]{2}\-[0-9]{2}\ [0-9]{2}:[0-9]{2}:[0-9]{2};
+                                                                                [A-Z]{3};[+-]*[0-9]+\.[0-9]{4}$")
+                if [ "$LINE" -ne 0 ] ; then
                     echo "ERROR: Wrong or damaged LOG used, please check your LOG." >&2
                     exit 1
                 else
@@ -109,7 +110,8 @@ ERROR_fun () { #checks basic syntax and returns errors and even more breaf help
             exit 1
             ;;
         8)
-            echo "ERROR: You can use only one name at once. Maybe you just misspelled something, may want to check '--help'." >&2
+            echo "ERROR: You can use only one name at once. Maybe you just misspelled something,
+                                                                may want to check '--help'." >&2
             exit 1
             ;;
     esac
@@ -191,9 +193,10 @@ while [ "$#" -gt 0 ]; do #checks for every input
             ;; # -||- BEFORE -||-
         -c)
             FLC_counter=$((FLC_counter+1))
+            #PQ=$(echo "$2" | grep -Pq "^[A-Z]{3}$")
             if [ "$FLC_counter" -eq 1 ]; then
                 FLC="$2"
-            else
+            elif [ "$FLC_counter" -gt 1 ]; then
                 FLC="${FLC} $2"
             fi
             shift 2
@@ -234,6 +237,7 @@ while [ "$#" -gt 0 ]; do #checks for every input
             ;;
         *)
             NAME_counter=$((NAME_counter+1))
+            #PQ=$(echo "$1" | grep -Pq "^[!-~]+$")
             if [ "$NAME_counter" -eq 1 ]; then #checks for misspelled commands or name overusage
                 NAME="$1"
                 shift 1
